#!/usr/bin/env python3

def eachSquare(sidelength=100):
    for i in range(4):
        forward(sidelength)
        right(90)
        speed(10)

from turtle import *
shape('turtle')

for j in range(20):
    speed(10)
    eachSquare()
    right(15)
